fpgen CI: Prevent make-fp-mr from returning a failure when the MR already exists and has been updated and there are no other errors
See merge request https://gitlab.com/kicad/libraries/kicad-library-utils/-/merge_requests/718

diff --git a/tools/gitlabci/gitlab-ci-fpgen.yml b/tools/gitlabci/gitlab-ci-fpgen.yml
--- a/tools/gitlabci/gitlab-ci-fpgen.yml
+++ b/tools/gitlabci/gitlab-ci-fpgen.yml
@@ -199,6 +199,8 @@ make-fp-mr:
     - export MR_DESCRIPTION="Output of merge request ${CI_MERGE_REQUEST_PROJECT_URL}/-/merge_requests/${CI_MERGE_REQUEST_IID} ${CI_MERGE_REQUEST_TITLE}"
     - export MR_TITLE="Generator MR ${CI_MERGE_REQUEST_IID} ${CI_MERGE_REQUEST_TITLE}"
     - |
+      echo "Creating the FP MR..."
+      set +e
       MR_CREATION_OUTPUT=$(
         gitlab --private-token "${MR_TOKEN}" \
         project-merge-request create \
@@ -214,21 +216,24 @@ make-fp-mr:
         2>&1
       )
       EXIT_CODE=$?
-
+      set -e
+      echo "$MR_CREATION_OUTPUT"
       if [ $EXIT_CODE -ne 0 ]; then
-        echo "$MR_CREATION_OUTPUT"
         # Check if the failure is due to the MR already existing.
-        if echo "$MR_CREATION_OUTPUT" | grep -q "Another open merge request already exists for this source branch"; then
+        if echo "$MR_CREATION_OUTPUT" | grep -q "409"; then
           # MR_CREATION_OUTPUT is something like "Impossible to create object (409: ['Another open merge request already exists for this source branch: !4472'])"
           IID=$(echo "$MR_CREATION_OUTPUT" | grep -o '!.*' | awk -F'!' '{ print $2 }' | awk -F']' '{ print $1 }')
         else
           # Unknown error - we return an error code:
+          echo "Unknown error code!"
           exit 1
         fi
       else
-        IID=$(echo "$MR_CREATION_OUTPUT" | awk '{print $3}')
+        IID=$(echo "$MR_CREATION_OUTPUT" | grep "^iid: " | awk '{print $2}')
       fi
       echo "Merge request URL https://gitlab.com/kicad/libraries/kicad-footprints/-/merge_requests/${IID}"
+
+
 
 make-3d-mr:
   stage: Footprint Generate
