fpgen CI: Prevent make-fp-mr from returning a failure when the MR already exists and has been updated and there are no other errors
See merge request https://gitlab.com/kicad/libraries/kicad-library-utils/-/merge_requests/712

diff --git a/tools/gitlabci/gitlab-ci-fpgen.yml b/tools/gitlabci/gitlab-ci-fpgen.yml
--- a/tools/gitlabci/gitlab-ci-fpgen.yml
+++ b/tools/gitlabci/gitlab-ci-fpgen.yml
@@ -199,18 +199,36 @@ make-fp-mr:
     - export MR_DESCRIPTION="Output of merge request ${CI_MERGE_REQUEST_PROJECT_URL}/-/merge_requests/${CI_MERGE_REQUEST_IID} ${CI_MERGE_REQUEST_TITLE}"
     - export MR_TITLE="Generator MR ${CI_MERGE_REQUEST_IID} ${CI_MERGE_REQUEST_TITLE}"
     - |
-      gitlab --private-token "${MR_TOKEN}" \
-      project-merge-request create \
-      --project-id 68268360 \
-      --source-branch "$branchname" \
-      --target-branch master \
-      --allow-collaboration true \
-      --squash true \
-      --remove-source-branch true \
-      --target-project-id 21601606 \
-      --title "$MR_TITLE" \
-      --description "$MR_DESCRIPTION" \
-      2>&1 | awk '/^iid: / {print "Merge request URL https://gitlab.com/kicad/libraries/kicad-footprints/-/merge_requests/" $2}'
+      MR_CREATION_OUTPUT=$(
+        gitlab --private-token "${MR_TOKEN}" \
+        project-merge-request create \
+        --project-id 68268360 \
+        --source-branch "$branchname" \
+        --target-branch master \
+        --allow-collaboration true \
+        --squash true \
+        --remove-source-branch true \
+        --target-project-id 21601606 \
+        --title "$MR_TITLE" \
+        --description "$MR_DESCRIPTION" \
+        2>&1
+      )
+      EXIT_CODE=$?
+
+      if [ $EXIT_CODE -ne 0 ]; then
+        echo "$MR_CREATION_OUTPUT"
+        # Check if the failure is due to the MR already existing.
+        if echo "$MR_CREATION_OUTPUT" | grep -q "Another open merge request already exists for this source branch"; then
+          # MR_CREATION_OUTPUT is something like "Impossible to create object (409: ['Another open merge request already exists for this source branch: !4472'])"
+          IID=$(echo "$MR_CREATION_OUTPUT" | grep -o '!.*' | awk -F'!' '{ print $2 }' | awk -F']' '{ print $1 }')
+        else
+          # Unknown error - we return an error code:
+          exit 1
+        fi
+      else
+        IID=$(echo "$MR_CREATION_OUTPUT" | awk '{print $3}')
+      fi
+      echo "Merge request URL https://gitlab.com/kicad/libraries/kicad-footprints/-/merge_requests/${IID}"
 
 make-3d-mr:
   stage: Footprint Generate
